global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: production
    project: smart-agri-city

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:3000"]
        labels:
          service: gateway

  - job_name: "php-farmer"
    metrics_path: /metrics
    static_configs:
      - targets: ["php-farmer:8000"]
        labels:
          service: php-farmer

  - job_name: "php-crop"
    metrics_path: /metrics
    static_configs:
      - targets: ["php-crop:8001"]
        labels:
          service: php-crop

  - job_name: "php-irrigation"
    metrics_path: /metrics
    static_configs:
      - targets: ["php-irrigation:8002"]
        labels:
          service: php-irrigation

  - job_name: "python-ml"
    metrics_path: /metrics
    static_configs:
      - targets: ["python-ml:5000"]
        labels:
          service: python-ml

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
        labels:
          service: rabbitmq
